from __future__ import annotations


class SessionState:
    CREATED = "CREATED"
    UPLOAD_PENDING = "UPLOAD_PENDING"
    UPLOADED_PENDING_REVIEW = "UPLOADED_PENDING_REVIEW"
    VERIFYING = "VERIFYING"
    VERIFIED_GREEN = "VERIFIED_GREEN"
    VERIFIED_AMBER = "VERIFIED_AMBER"
    VERIFIED_RED = "VERIFIED_RED"
    PENDING_HUMAN_REVIEW = "PENDING_HUMAN_REVIEW"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    HUMAN_REJECTED = "HUMAN_REJECTED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    ABANDONED_VERIFYING = "ABANDONED_VERIFYING"
    FAILED_RETRIABLE = "FAILED_RETRIABLE"
    FAILED_PURGED = "FAILED_PURGED"
    PENDING_CLEANUP = "PENDING_CLEANUP"
    PURGE_COMPLETE = "PURGE_COMPLETE"


VERIFIED_STATES = {
    SessionState.VERIFIED_GREEN,
    SessionState.VERIFIED_AMBER,
    SessionState.VERIFIED_RED,
}


HUMAN_FINAL_STATES = {
    SessionState.HUMAN_APPROVED,
    SessionState.HUMAN_REJECTED,
    SessionState.MANUAL_REVIEW_REQUIRED,
}


TERMINAL_STATES = HUMAN_FINAL_STATES | {
    SessionState.FAILED_RETRIABLE,
    SessionState.FAILED_PURGED,
    SessionState.PURGE_COMPLETE,
}
