from __future__ import annotations


class SessionState:
    CREATED = "CREATED"
    UPLOAD_PENDING = "UPLOAD_PENDING"
    UPLOADED_PENDING_REVIEW = "UPLOADED_PENDING_REVIEW"
    VERIFYING = "VERIFYING"
    VERIFIED_GREEN = "VERIFIED_GREEN"
    VERIFIED_AMBER = "VERIFIED_AMBER"
    VERIFIED_RED = "VERIFIED_RED"
    ABANDONED_VERIFYING = "ABANDONED_VERIFYING"
    FAILED_RETRIABLE = "FAILED_RETRIABLE"
    FAILED_PURGED = "FAILED_PURGED"
    PENDING_CLEANUP = "PENDING_CLEANUP"
    PURGE_COMPLETE = "PURGE_COMPLETE"


VERIFIED_STATES = {
    SessionState.VERIFIED_GREEN,
    SessionState.VERIFIED_AMBER,
    SessionState.VERIFIED_RED,
}


TERMINAL_STATES = VERIFIED_STATES | {
    SessionState.FAILED_RETRIABLE,
    SessionState.FAILED_PURGED,
    SessionState.PURGE_COMPLETE,
}
